# Default values for template-node-typescript.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global: {}

replicaCount: 1
logLevel: "debug"

profiles:
  active: ocp

credentials:
  dbusername: "Ym9va2luZ21zZGI="
  dbpassword: "Ym9va2luZ21zZGI="
  mqusername: "YXBwdXNlcg=="
  mqpassword: "cGFzc3cwcmQ="

datasources:
  dburl: "jdbc:mysql://mysql-cargo-dev.bluecargo-dev:3306/bookingmsdb?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=EST&useSSL=false"
  mqhost: "rabbitmq-cargo-dev-headless"
  mqport: "5672"

image:
  repository: replace
  tag: replace
  pullPolicy: IfNotPresent
  port: 9081

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

route:
  enabled: false

ingress:
  enabled: true
  appid:
    enabled: false
    # web or app - https://cloud.ibm.com/docs/services/appid?topic=appid-kube-auth
    requestType: web

#  host: hello
  namespaceInHost: true
  subdomain: containers.appdomain.cloud
  path: "/"

#  tlsSecretName: ""

vcsInfo:
  repoUrl: "https://github.com/tcs-sandbox-team-one/cargo-booking-liberty-api.git"
  branch: "master"

partOf: "cargotracker-backend-dev"

connectsTo: "mysql-cargo-dev, rabbitmq-cargo-dev, cargo-routing-liberty-api"

runtime: liberty
