apiVersion: v1
data:
  bookingdb.user.name: {{ .Values.credentials.dbusername }}
  bookingdb.user.password: {{ .Values.credentials.dbpassword }}
  rabbitmq.user.name: {{ .Values.credentials.mqusername }}
  rabbitmq.user.password: {{ .Values.credentials.mqpassword }}   
kind: Secret
metadata:
  name: cargotracker-booking-credentials
type: Opaque